[package]
name = "i3-open-next-ws"
version = "0.1.1"
edition = "2018"
description = "A companion utility to i3wm for managing workspaces."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta"
swayipc = "2.7.2"
